# systemove informace
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: disk_use
      arg: /config
    - type: disk_free
    - type: memory_free
    - type: memory_use
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: swap_free
    - type: swap_use
    - type: swap_use_percent

#  teplota procesoru
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 10
  
# MariaDB velikost
- platform: sql
  db_url: !secret recorder_db_url
  queries:
    - name: MariaDB velikost
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: MB
      
# InfluxDB velikost
- platform: influxdb
  host: a0d7b954-influxdb
  port: 8086
  username: !secret influx_username
  password: !secret influx_password
  queries:
    - name: InfluxDB velikost
      unit_of_measurement: MB
      value_template: '{{ (value | float / 1024 /1024) | round(1) }}'
      group_function: mean
      measurement: '"monitor"."shard"'
      database: _internal
      where: 'time > now() - 1m AND "database"=''homeassistant'''
      field: diskBytes 