- id: change_thema
  alias: 'Frontend: změna tématu'
  trigger:
  - platform: state
    entity_id: input_select.theme
  - platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: '{{ states.input_select.theme.state }}'
- id: '1676470917777'
  alias: Odvlhčovač - večerní vypnutí
  description: Vypnutí odvlhčovače každý večer
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 1f286535060b37794deddf2cf4e02b47
    entity_id: switch.odvlhcovac_ov2220
    domain: switch
  mode: single
- id: '1676470978930'
  alias: Odvlhčovač - ranní spuštění
  description: Spuštění odvlhčovače každé ráno
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 1f286535060b37794deddf2cf4e02b47
    entity_id: switch.odvlhcovac_ov2220
    domain: switch
  mode: single
- id: '1676471091438'
  alias: Notifikace - odvlhčovač plná nádrž
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.odvlhcovac_ov2220_nadrz
    attribute: raw_state
    from: 0
    to: 8
  condition: []
  action:
  - device_id: b385cab1771708084fc77aa7f7695937
    domain: mobile_app
    type: notify
    message: 'Plná nádrž '
    title: Odvlhcovač
  mode: single
- id: '1685450310751'
  alias: Notifikace - odpadky
  description: Notifikace na vyvážení popelnic
  trigger:
  - platform: calendar
    event: start
    offset: 0:0:0
    entity_id: calendar.odpadky
  condition: []
  action:
  - device_id: b385cab1771708084fc77aa7f7695937
    domain: mobile_app
    type: notify
    title: Odpadky
    message: '{{ states(''sensor.odpad_typ'') }}'
  mode: single
