- id: change_thema
  alias: 'Frontend: změna tématu'
  trigger:
  - platform: state
    entity_id: input_select.theme
  - platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: '{{ states.input_select.theme.state }}'
- id: '1666183776295'
  alias: Notifikace odpadky - směs
  description: Notifikace na vyvyzení popelnice
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: sensor.general_waste
    attribute: days
    state: 0
  action:
  - service: notify.mobile_app_redmi_note_8_pro
    data:
      title: Odpadky
      message: Směs
  mode: single
- id: '1666183903283'
  alias: Notifikace odpadky - papír
  description: Notifikace na vyvezení popelnice
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: sensor.paper
    attribute: days
    state: 0
  action:
  - service: notify.mobile_app_redmi_note_8_pro
    data:
      title: Odpadky
      message: Papír
  mode: single
- id: '1666184054627'
  alias: Notifikace odpadky - plasty
  description: Notifikace na vyvezení popelnice
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: sensor.plastic
    attribute: days
    state: 0
  action:
  - service: notify.mobile_app_redmi_note_8_pro
    data:
      message: Plasty
      title: Odpadky
  mode: single
- id: '1676470917777'
  alias: Odvlhčovač - večerní vypnutí
  description: Vypnutí odvlhčovače každý večer
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 1f286535060b37794deddf2cf4e02b47
    entity_id: switch.odvlhcovac_ov2220
    domain: switch
  mode: single
- id: '1676470978930'
  alias: Odvlhčovač - ranní spuštění
  description: Spuštění odvlhčovače každé ráno
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 1f286535060b37794deddf2cf4e02b47
    entity_id: switch.odvlhcovac_ov2220
    domain: switch
  mode: single
- id: '1676471091438'
  alias: Notifikace - odvlhčovač plná nádrž
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.odvlhcovac_ov2220_nadrz
    attribute: raw_state
    from: 0
    to: 8
  condition: []
  action:
  - device_id: 6cf5d71fbaab6cc9446e7b7d8fe2750f
    domain: mobile_app
    type: notify
    message: Odvlhčovač
    title: Plná nádrž
  mode: single
