- id: change_thema
  alias: 'Frontend: změna tématu'
  trigger:
  - platform: state
    entity_id: input_select.theme
  - platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: '{{ states.input_select.theme.state }}'
- id: '1666183776295'
  alias: Notifikace odpadky - směs
  description: Notifikace na vyvyzení popelnice
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: sensor.general_waste
    attribute: days
    state: 0
  action:
  - service: notify.mobile_app_redmi_note_8_pro
    data:
      title: Odpadky
      message: Směs
  mode: single
- id: '1666183903283'
  alias: Notifikace odpadky - papír
  description: Notifikace na vyvezení popelnice
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: sensor.paper
    attribute: days
    state: 0
  action:
  - service: notify.mobile_app_redmi_note_8_pro
    data:
      title: Odpadky
      message: Papír
  mode: single
- id: '1666184054627'
  alias: Notifikace odpadky - plasty
  description: Notifikace na vyvezení popelnice
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: sensor.plastic
    attribute: days
    state: 0
  action:
  - service: notify.mobile_app_redmi_note_8_pro
    data:
      message: Plasty
      title: Odpadky
  mode: single
- id: '1675859692648'
  alias: Sušička - notifikace
  description: Notifikace plné nádrže odvlhčovače
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.susicka_nadrz
    attribute: raw_state
    from: 0
    to: 8
  condition: []
  action:
  - service: notify.mobile_app_redmi_note_8_pro
    data:
      message: Plná nádrž!!
      title: Sušička
  mode: single
- id: '1676308017304'
  alias: Sušička - večení vypnutí
  description: Vypnutí sušičky každý večer
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 1f286535060b37794deddf2cf4e02b47
    entity_id: switch.susicka
    domain: switch
  mode: single
- id: '1676314903687'
  alias: Sušička - ranní zapnutí
  description: Zapnutí sušičky každý den ráno
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 1f286535060b37794deddf2cf4e02b47
    entity_id: switch.susicka
    domain: switch
  mode: single
