#chlazeni procesoru
- platform: generic_thermostat
  name: RPI Cooling Fan Controller
  heater: switch.rpi_cooling_fan
  target_sensor: sensor.cpu_temperature
  min_temp: 55
  max_temp: 80
  ac_mode: true
  target_temp: 80
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  min_cycle_duration:
    seconds: 30
  keep_alive:
    minutes: 5
  initial_hvac_mode: "cool"