# monitor free RAM
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: memory_free

# monitor CPU temperature for fan
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 10